# Generated by Django 2.1.5 on 2019-02-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_politiciandetail_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='assembly_constituency_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.AssemblyConstituencyName'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='fathers_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.Party'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.CharField(choices=[('Politician', 'Politician'), ('Supporter', 'Supporter')], max_length=40, null=True),
        ),
    ]
